/* Trappy Flump, browser audio.
 *
 * Sits next to game.js and listens to the events the game emits; the game
 * itself never touches audio. All files in audio/ are generated by
 * assets/audio/gen.py (see assets/audio/SOURCES.md).
 *
 * TrappyAudio.attach(game, canvas) returns { sound, music, setSound(on),
 * setMusic(on), onchange }. Nothing is loaded or created until the first
 * pointerdown on the canvas, which is also what browsers require before
 * playing. The game's own menu buttons emit "sound"/"music"; this layer owns
 * the preference and mirrors it back with game.setAudio() so the buttons
 * draw right. `onchange` (settable) fires after any change from either side.
 */
(function (root) {
	"use strict";

	var BASE = "audio/";
	var SFX = ["flap", "score", "score2", "hit", "fall", "over", "laugh", "best", "news", "news_end",
		"inflation", "siren", "missile", "boom", "float", "crowd", "ui", "wind",
		"star", "power", "smash", "cash", "jackpot", "dark", "gust",
		"voice_china", "voice_inflation", "voice_ratecut", "voice_election", "voice_best", "voice_milestone",
		"voice_immunity", "voice_shutdown", "voice_stimulus", "voice_hurricane"];
	var MUSIC = ["music_menu", "music_menu_intro", "music_play"];
	// a one-shot that plays through once before its loop, sample-aligned
	var INTRO = { music_menu: "music_menu_intro" };
	var INTRO_OF = { music_menu_intro: "music_menu" };
	var VOICE_BY_EVENT = { "CHINA TARIFFS": "voice_china", "INFLATION": "voice_inflation",
		"RATE CUT": "voice_ratecut", "ELECTION": "voice_election", "IMMUNITY": "voice_immunity",
		"SHUTDOWN": "voice_shutdown", "STIMULUS": "voice_stimulus", "HURRICANE": "voice_hurricane" };
	var STING_BY_EVENT = { "INFLATION": "inflation", "RATE CUT": "float", "ELECTION": "crowd",
		"IMMUNITY": "star", "SHUTDOWN": "dark", "STIMULUS": "jackpot", "HURRICANE": "gust" };
	var WIND_VOL = 0.5, STORM_VOL = 1.0, POWER_VOL = 0.55;
	var MILESTONES = { 10: true, 25: true, 50: true, 100: true };
	var KEY_SOUND = "tf_sound", KEY_MUSIC = "tf_music";

	function pref(key, dflt) {
		try { var v = localStorage.getItem(key); return v === null ? dflt : v === "1"; } catch (e) { return dflt; }
	}
	function save(key, on) { try { localStorage.setItem(key, on ? "1" : "0"); } catch (e) { /* private mode */ } }

	function attach(game, canvas) {
		var AC = root.AudioContext || root.webkitAudioContext;
		var api = { sound: pref(KEY_SOUND, true), music: pref(KEY_MUSIC, false), setSound: setSound, setMusic: setMusic, onchange: null };
		function sync() {
			game.setAudio(api.sound, api.music);
			if (api.onchange) api.onchange(api);
		}
		game.on("sound", function (on) { api.setSound(on); });
		game.on("music", function (on) { api.setMusic(on); });
		sync();
		if (!AC) {
			// no Web Audio: the switches still flip so the menu buttons respond
			api.setSound = function (on) { api.sound = !!on; save(KEY_SOUND, api.sound); sync(); };
			api.setMusic = function (on) { api.music = !!on; save(KEY_MUSIC, api.music); sync(); };
			return api;
		}

		var ctx = null, master, sfxBus, voiceBus, musicBus, duckGain;
		var buffers = {};
		var loops = {};          // id -> {src, gain}
		var musicId = null, musicSrc = null, introSrc = null, musicFromLoop = false;
		var canOgg = !!(document.createElement("audio").canPlayType("audio/ogg; codecs=vorbis"));
		var timers = [];

		function ensure() {
			if (ctx) { if (ctx.state === "suspended") ctx.resume(); return; }
			ctx = new AC();
			master = ctx.createGain(); master.connect(ctx.destination);
			sfxBus = ctx.createGain(); sfxBus.connect(master);
			voiceBus = ctx.createGain(); voiceBus.gain.value = 0.9; voiceBus.connect(master);
			duckGain = ctx.createGain(); duckGain.connect(master);
			musicBus = ctx.createGain(); musicBus.gain.value = 0.45; musicBus.connect(duckGain);
			applyPrefs();
			SFX.forEach(function (id) { load(id, id + ".wav"); });
			if (canOgg) MUSIC.forEach(function (id) { load(id, id + ".ogg"); });
		}

		function load(id, file) {
			fetch(BASE + file).then(function (r) { return r.arrayBuffer(); })
				.then(function (ab) { return ctx.decodeAudioData(ab); })
				.then(function (buf) { buffers[id] = buf; loaded(id); })
				.catch(function () { buffers[id] = null; loaded(id); });   // missing file: stay silent
		}
		function loaded(id) {
			// something asked for this before it was decoded
			if (loops[id] && !loops[id].src) startLoop(id, loops[id].vol);
			var m = INTRO_OF[id] || id;
			if (musicId === m && !musicSrc) startMusic(m, musicFromLoop);
		}

		function play(id, opts) {
			opts = opts || {};
			if (!ctx || !api.sound) return;
			var buf = buffers[id];
			if (!buf) return;
			var src = ctx.createBufferSource();
			src.buffer = buf;
			if (opts.pitch) src.playbackRate.value = opts.pitch;
			var g = ctx.createGain();
			g.gain.value = opts.vol == null ? 1 : opts.vol;
			src.connect(g);
			g.connect(opts.voice ? voiceBus : sfxBus);
			src.start(ctx.currentTime + (opts.delay || 0));
			if (opts.voice) duck(0.9 + buf.duration);
		}

		function later(sec, fn) { timers.push(setTimeout(fn, sec * 1000)); }
		function clearTimers() { timers.forEach(clearTimeout); timers = []; }

		function startLoop(id, vol) {
			if (!ctx) return;
			var rec = loops[id] || (loops[id] = { src: null, gain: null, vol: vol });
			rec.vol = vol;
			if (rec.src || !buffers[id]) return;
			var src = ctx.createBufferSource();
			src.buffer = buffers[id]; src.loop = true;
			var g = ctx.createGain(); g.gain.value = 0;
			g.gain.linearRampToValueAtTime(vol, ctx.currentTime + 0.3);
			src.connect(g); g.connect(sfxBus); src.start();
			rec.src = src; rec.gain = g;
		}
		function stopLoop(id) {
			var rec = loops[id];
			if (!rec) return;
			if (rec.src) {
				var src = rec.src, g = rec.gain;
				g.gain.setTargetAtTime(0, ctx.currentTime, 0.1);
				setTimeout(function () { try { src.stop(); } catch (e) { /* already stopped */ } }, 500);
			}
			delete loops[id];
		}
		function stopAllLoops() { Object.keys(loops).forEach(stopLoop); }
		function loopVolume(id, vol, sec) {
			var rec = loops[id];
			if (!rec) return;
			rec.vol = vol;
			if (rec.gain) rec.gain.gain.setTargetAtTime(vol, ctx.currentTime, (sec || 0.5) / 3);
		}

		function startMusic(id, fromLoop) {
			// fromLoop: skip the intro, straight into the loop (after a death;
			// the entrance is for arriving at the menu, not for every crash)
			musicId = id; musicFromLoop = !!fromLoop;
			stopSources();
			if (!ctx || !api.music || !buffers[id]) return;
			var introId = INTRO[id], intro = fromLoop ? null : buffers[introId];
			if (introId && !fromLoop && intro === undefined) return;   // still decoding; loaded() retries
			var at = ctx.currentTime;
			if (intro) {
				var pre = ctx.createBufferSource();
				pre.buffer = intro; pre.connect(musicBus); pre.start(at);
				introSrc = pre; at += intro.duration;
			}
			var src = ctx.createBufferSource();
			src.buffer = buffers[id]; src.loop = true;
			src.connect(musicBus); src.start(at);
			musicSrc = src;
		}
		function stopSources() {
			if (introSrc) { try { introSrc.stop(); } catch (e) { /* */ } introSrc = null; }
			if (musicSrc) { try { musicSrc.stop(); } catch (e) { /* */ } musicSrc = null; }
		}
		function stopMusic() { stopSources(); }
		function duck(sec) {
			if (!ctx) return;
			var t = ctx.currentTime;
			duckGain.gain.cancelScheduledValues(t);
			duckGain.gain.setTargetAtTime(0.35, t, 0.05);
			duckGain.gain.setTargetAtTime(1, t + sec, 0.3);
		}

		function applyPrefs() {
			if (!ctx) return;
			sfxBus.gain.value = api.sound ? 1 : 0;
			voiceBus.gain.value = api.sound ? 0.9 : 0;
			if (api.music) { if (musicId && !musicSrc) startMusic(musicId, musicFromLoop); } else stopMusic();
		}
		function setSound(on) { api.sound = !!on; save(KEY_SOUND, api.sound); applyPrefs(); if (on) play("ui"); sync(); }
		function setMusic(on) { api.music = !!on; save(KEY_MUSIC, api.music); ensure(); applyPrefs(); sync(); }

		// ---- unlock on the same click that focuses the frame ----
		canvas.addEventListener("pointerdown", ensure, true);

		// ---- game events ----
		game.on("start", function () {
			clearTimers();
			startLoop("wind", WIND_VOL);
			startMusic("music_play");
		});
		game.on("flap", function () { play("flap", { pitch: 0.95 + Math.random() * 0.1 }); });
		game.on("resume", function () { if (ctx) ctx.resume(); });
		game.on("pause", function () { if (ctx && ctx.state === "running") ctx.suspend(); });
		game.on("score", function (score) {
			play(game.event === "ELECTION" ? "score2" : "score");
			if (MILESTONES[score]) play("voice_milestone", { voice: true, delay: 0.15 });
		});
		game.on("event", function (e) {
			var name = e.name;
			play("news");
			if (STING_BY_EVENT[name]) play(STING_BY_EVENT[name], { delay: 0.55 });
			if (e.missiles) startLoop("siren", 0.35);
			if (e.star) {
				// the star riff takes over from the music for the whole event
				duck(e.dur);
				later(0.9, function () { startLoop("power", POWER_VOL); });
			}
			if (e.storm) loopVolume("wind", STORM_VOL, 1.0);
			if (VOICE_BY_EVENT[name]) play(VOICE_BY_EVENT[name], { voice: true, delay: 0.6 });
		});
		game.on("eventEnd", function () {
			play("news_end");
			stopLoop("siren");
			stopLoop("power");
			loopVolume("wind", WIND_VOL, 1.5);
		});
		game.on("missile", function () { play("missile", { vol: 0.7, pitch: 0.9 + Math.random() * 0.2 }); });
		game.on("smash", function () { play("smash", { vol: 0.8, pitch: 0.92 + Math.random() * 0.16 }); });
		game.on("missileSmash", function () { play("boom", { vol: 0.4, pitch: 1.25 }); });
		game.on("cash", function () { play("cash", { pitch: 0.97 + Math.random() * 0.08 }); });
		game.on("ui", function () { play("ui"); });   // achievements open / close
		game.on("dead", function (info) {
			clearTimers();
			stopAllLoops();
			stopMusic();
			play(info.cause === "missile" ? "boom" : "hit");
			play("fall", { delay: 0.12 });
			later(0.55, function () { play("over"); });
			later(1.05, function () { play("laugh", { vol: 0.8 }); });
			if (info.newBest) {
				later(0.7, function () { play("best"); });
				later(1.6, function () { play("voice_best", { voice: true }); });
			}
			later(2.2, function () { startMusic("music_menu", true); });
		});
		game.on("menu", function () {
			clearTimers();
			stopAllLoops();
			play("ui");
			startMusic("music_menu");
		});
		musicId = "music_menu";

		return api;
	}

	root.TrappyAudio = { attach: attach };
})(typeof self !== "undefined" ? self : this);
